package com.example.demo.entities;
// Generated May 23, 2018 1:38:46 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "shophandmade", uniqueConstraints = @UniqueConstraint(columnNames = "TEN_DANGNHAP"))
public class Account implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@Pattern(regexp = "^(.+)@(.+\\.+.+)$", message = "{field.email.invalid}")
	private String email;
	private String password;
	private String position;
	@Size(min = 1, message = "{field.empty}")
	private String fullName;
	private String address;
	@Pattern(regexp = "(\\d{10,11})", message = "{field.phone.invalid}")
	private String phoneNumber;
	private Integer confirmation;

	public Account() {}

	public Account(String password, Integer confirmation, @Size(min = 1, message = "{field.empty}") String fullName,
			@Pattern(regexp = "(\\d{10,11})", message = "{field.phone.invalid}") String phoneNumber, String address) {
		super();
		this.password = password;
		this.confirmation = confirmation;
		this.fullName = fullName;
		this.phoneNumber = phoneNumber;
		this.address = address;
	}

	public Account(@Pattern(regexp = "^(.+)@(.+\\.+.+)$", message = "{field.email.invalid}") String email, String password, 
			@Size(min = 1, message = "{field.empty}") String fullName, String address, 
			@Pattern(regexp = "(\\d{10,11})", message = "{field.phone.invalid}") String phoneNumber) {
		super();
		this.email = email;
		this.password = password;
		this.fullName = fullName;
		this.address = address;
		this.phoneNumber = phoneNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TK", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TEN_DANGNHAP", unique = true, nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}
	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MAT_KHAU", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "CHUCVU", length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "TEN_KH", length = 200)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "DIACHI", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "SDT", length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "IS_CONFIRM")
	public Integer getConfirmation() {
		return this.confirmation;
	}

	public void setConfirmation(Integer confirmation) {
		this.confirmation = confirmation;
	}

	@Override
	public String toString() {
		return "Account [id=" + id + ", email=" + email + ", password=" + password + ", position=" + position
				+ ", fullName=" + fullName + ", address=" + address + ", phoneNumber=" + phoneNumber + ", confirmation="
				+ confirmation + "]";
	}

}