package com.example.demo.entities;
// Generated May 23, 2018 1:38:46 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Loaihang generated by hbm2java
 */
@Entity
@Table(name = "loaihang", catalog = "shophandmade")
public class Category implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCategory;
	private String nameCategory;
	private Integer isDelete;

	public Category() {
	}

	public Category(String nameCategory) {
		this.nameCategory = nameCategory;
	}

	public Category(String nameCategory, Integer isDelete) {
		this.nameCategory = nameCategory;
		this.isDelete = isDelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_LOAIHANG", unique = true, nullable = false)
	public Integer getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(Integer idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "TEN_LOAIHANG", nullable = false, length = 100)
	public String getNameCategory() {
		return this.nameCategory;
	}

	public void setNameCategory(String nameCategory) {
		this.nameCategory = nameCategory;
	}

	@Column(name = "IS_DELETE")
	public Integer getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Integer isDelete) {
		this.isDelete = isDelete;
	}

	@Override
	public String toString() {
		return "Category [idCategory=" + idCategory + ", nameCategory=" + nameCategory + ", isDelete=" + isDelete + "]";
	}
	
}
