package com.example.demo.entities;
// Generated May 23, 2018 1:38:46 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitietdonhang generated by hbm2java
 */
@Entity
@Table(name = "chitietdonhang", catalog = "shophandmade")
public class Chitietdonhang implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ChitietdonhangId id;
	private Order order;
	private Product sanpham;

	public Chitietdonhang() {
	}

	public Chitietdonhang(ChitietdonhangId id) {
		this.id = id;
	}

	public Chitietdonhang(ChitietdonhangId id, Order order, Product sanpham) {
		this.id = id;
		this.order = order;
		this.sanpham = sanpham;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idDonhang", column = @Column(name = "ID_DONHANG")),
			@AttributeOverride(name = "idSanpham", column = @Column(name = "ID_SANPHAM")),
			@AttributeOverride(name = "soLuong", column = @Column(name = "SO_LUONG")) })
	public ChitietdonhangId getId() {
		return this.id;
	}

	public void setId(ChitietdonhangId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DONHANG", insertable = false, updatable = false)
	public Order getDonhang() {
		return this.order;
	}

	public void setDonhang(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SANPHAM", insertable = false, updatable = false)
	public Product getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(Product sanpham) {
		this.sanpham = sanpham;
	}

	@Override
	public String toString() {
		return "Chitietdonhang [id=" + id + ", order=" + order + ", sanpham=" + sanpham + "]";
	}

}
