package com.example.demo.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "donhang", catalog = "shophandmade")
public class Order implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer idOrder;
	private Date orderDate;
	private Integer totalAmount;
	private String customerName;
	private String phoneNumber;
	private String address;
	private String email;
	private Integer status;

	public Order() {
	}

	public Order(String tenKhachhang) {
		this.customerName = tenKhachhang;
	}

	public Order(Date ngayDh, Integer tongTien, String tenKhachhang, String sdt, String diachi, String email,
			Integer status) {
		this.orderDate = ngayDh;
		this.totalAmount = tongTien;
		this.customerName = tenKhachhang;
		this.phoneNumber = sdt;
		this.address = diachi;
		this.email = email;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_DONHANG", unique = true, nullable = false)
	public Integer getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(Integer idDonhang) {
		this.idOrder = idDonhang;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NGAY_DH", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date ngayDh) {
		this.orderDate = ngayDh;
	}

	@Column(name = "TONG_TIEN")
	public Integer getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(Integer tongTien) {
		this.totalAmount = tongTien;
	}

	@Column(name = "TEN_KHACHHANG", nullable = false, length = 200)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String tenKhachhang) {
		this.customerName = tenKhachhang;
	}

	@Column(name = "SDT", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String sdt) {
		this.phoneNumber = sdt;
	}

	@Column(name = "DIACHI", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String diachi) {
		this.address = diachi;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String generateStatus() {
		if (status == 0) {
			return "Đang xác nhận";
		} else if (status == 1) {
			return "Đã xác nhận";
		} else if (status == 2) {
			return "Đã giao hàng";
		}
		return "Đã hủy đơn hàng";
	}
	public String generateDate() {
		SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
		
		return formatter.format(orderDate);
	}

	@Override
	public String toString() {
		return  "Mã ĐH: " + idOrder + 
				"\nNgày đặt hàng: " + generateDate() + 
				"\nTổng tiền: " + totalAmount + 
				"\nTình trạng: " + generateStatus();
	}

}
