package com.example.demo.entities;
// Generated May 2, 2018 12:42:50 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cmt generated by hbm2java
 */
@Entity
@Table(name = "cmt", catalog = "shophandmade")
public class Cmt implements java.io.Serializable {

	private Integer idCmt;
	private Sanpham sanpham;
	private Taikhoan taikhoan;
	private Date thoiGian;
	private String noiDung;

	public Cmt() {
	}

	public Cmt(Sanpham sanpham, Taikhoan taikhoan, Date thoiGian) {
		this.sanpham = sanpham;
		this.taikhoan = taikhoan;
		this.thoiGian = thoiGian;
	}

	public Cmt(Sanpham sanpham, Taikhoan taikhoan, Date thoiGian, String noiDung) {
		this.sanpham = sanpham;
		this.taikhoan = taikhoan;
		this.thoiGian = thoiGian;
		this.noiDung = noiDung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_CMT", unique = true, nullable = false)
	public Integer getIdCmt() {
		return this.idCmt;
	}

	public void setIdCmt(Integer idCmt) {
		this.idCmt = idCmt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SANPHAM", nullable = false)
	public Sanpham getSanpham() {
		return this.sanpham;
	}

	public void setSanpham(Sanpham sanpham) {
		this.sanpham = sanpham;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TK", nullable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THOI_GIAN", nullable = false, length = 19)
	public Date getThoiGian() {
		return this.thoiGian;
	}

	public void setThoiGian(Date thoiGian) {
		this.thoiGian = thoiGian;
	}

	@Column(name = "NOI_DUNG", length = 500)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

}
