package com.example.demo.entities;
// Generated May 2, 2018 12:42:50 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tintuc generated by hbm2java
 */
@Entity
@Table(name = "tintuc", catalog = "shophandmade")
public class Tintuc implements java.io.Serializable {

	private Integer idTt;
	private Taikhoan taikhoan;
	private String title;
	private String context;
	private String nguoiDang;
	private Date ngayDang;

	public Tintuc() {
	}

	public Tintuc(Taikhoan taikhoan, Date ngayDang) {
		this.taikhoan = taikhoan;
		this.ngayDang = ngayDang;
	}

	public Tintuc(Taikhoan taikhoan, String title, String context, String nguoiDang, Date ngayDang) {
		this.taikhoan = taikhoan;
		this.title = title;
		this.context = context;
		this.nguoiDang = nguoiDang;
		this.ngayDang = ngayDang;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TT", unique = true, nullable = false)
	public Integer getIdTt() {
		return this.idTt;
	}

	public void setIdTt(Integer idTt) {
		this.idTt = idTt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TK", nullable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "TITLE", length = 500)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CONTEXT", length = 65535)
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Column(name = "NGUOI_DANG", length = 100)
	public String getNguoiDang() {
		return this.nguoiDang;
	}

	public void setNguoiDang(String nguoiDang) {
		this.nguoiDang = nguoiDang;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NGAY_DANG", nullable = false, length = 19)
	public Date getNgayDang() {
		return this.ngayDang;
	}

	public void setNgayDang(Date ngayDang) {
		this.ngayDang = ngayDang;
	}

}
