package com.example.demo.entities;
// Generated May 2, 2018 12:42:50 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDhofkh generated by hbm2java
 */
@Entity
@Table(name = "v_dhofkh", catalog = "shophandmade")
public class VDhofkh implements java.io.Serializable {

	private VDhofkhId id;

	public VDhofkh() {
	}

	public VDhofkh(VDhofkhId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDonhang", column = @Column(name = "ID_DONHANG", nullable = false)),
			@AttributeOverride(name = "ngayDh", column = @Column(name = "NGAY_DH", length = 19)),
			@AttributeOverride(name = "tongTien", column = @Column(name = "TONG_TIEN")),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS")),
			@AttributeOverride(name = "idTk", column = @Column(name = "ID_TK", nullable = false)) })
	public VDhofkhId getId() {
		return this.id;
	}

	public void setId(VDhofkhId id) {
		this.id = id;
	}

}
