package com.example.demo.entities;
// Generated May 2, 2018 12:42:50 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VDonhang generated by hbm2java
 */
@Entity
@Table(name = "v_donhang", catalog = "shophandmade")
public class VDonhang implements java.io.Serializable {

	private VDonhangId id;

	public VDonhang() {
	}

	public VDonhang(VDonhangId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idDonhang", column = @Column(name = "ID_DONHANG")),
			@AttributeOverride(name = "idSanpham", column = @Column(name = "ID_SANPHAM")),
			@AttributeOverride(name = "soLuong", column = @Column(name = "SO_LUONG")),
			@AttributeOverride(name = "tenSanpham", column = @Column(name = "TEN_SANPHAM", nullable = false, length = 200)) })
	public VDonhangId getId() {
		return this.id;
	}

	public void setId(VDonhangId id) {
		this.id = id;
	}

}
