package com.example.demo.entities;
// Generated May 2, 2018 12:42:50 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VLikemostId generated by hbm2java
 */
@Embeddable
public class VLikemostId implements java.io.Serializable {

	private int idSanpham;
	private String tenSanpham;
	private int gia;
	private String moTa;
	private int tinhTrang;
	private Integer idLoaihang;
	private Integer giamGia;
	private String images;
	private Integer soLuong;

	public VLikemostId() {
	}

	public VLikemostId(int idSanpham, String tenSanpham, int gia, int tinhTrang) {
		this.idSanpham = idSanpham;
		this.tenSanpham = tenSanpham;
		this.gia = gia;
		this.tinhTrang = tinhTrang;
	}

	public VLikemostId(int idSanpham, String tenSanpham, int gia, String moTa, int tinhTrang, Integer idLoaihang,
			Integer giamGia, String images, Integer soLuong) {
		this.idSanpham = idSanpham;
		this.tenSanpham = tenSanpham;
		this.gia = gia;
		this.moTa = moTa;
		this.tinhTrang = tinhTrang;
		this.idLoaihang = idLoaihang;
		this.giamGia = giamGia;
		this.images = images;
		this.soLuong = soLuong;
	}

	@Column(name = "ID_SANPHAM", nullable = false)
	public int getIdSanpham() {
		return this.idSanpham;
	}

	public void setIdSanpham(int idSanpham) {
		this.idSanpham = idSanpham;
	}

	@Column(name = "TEN_SANPHAM", nullable = false, length = 200)
	public String getTenSanpham() {
		return this.tenSanpham;
	}

	public void setTenSanpham(String tenSanpham) {
		this.tenSanpham = tenSanpham;
	}

	@Column(name = "GIA", nullable = false)
	public int getGia() {
		return this.gia;
	}

	public void setGia(int gia) {
		this.gia = gia;
	}

	@Column(name = "MO_TA", length = 500)
	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	@Column(name = "TINH_TRANG", nullable = false)
	public int getTinhTrang() {
		return this.tinhTrang;
	}

	public void setTinhTrang(int tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

	@Column(name = "ID_LOAIHANG")
	public Integer getIdLoaihang() {
		return this.idLoaihang;
	}

	public void setIdLoaihang(Integer idLoaihang) {
		this.idLoaihang = idLoaihang;
	}

	@Column(name = "GIAM_GIA")
	public Integer getGiamGia() {
		return this.giamGia;
	}

	public void setGiamGia(Integer giamGia) {
		this.giamGia = giamGia;
	}

	@Column(name = "IMAGES", length = 500)
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	@Column(name = "SO_LUONG")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VLikemostId))
			return false;
		VLikemostId castOther = (VLikemostId) other;

		return (this.getIdSanpham() == castOther.getIdSanpham())
				&& ((this.getTenSanpham() == castOther.getTenSanpham()) || (this.getTenSanpham() != null
						&& castOther.getTenSanpham() != null && this.getTenSanpham().equals(castOther.getTenSanpham())))
				&& (this.getGia() == castOther.getGia())
				&& ((this.getMoTa() == castOther.getMoTa()) || (this.getMoTa() != null && castOther.getMoTa() != null
						&& this.getMoTa().equals(castOther.getMoTa())))
				&& (this.getTinhTrang() == castOther.getTinhTrang())
				&& ((this.getIdLoaihang() == castOther.getIdLoaihang()) || (this.getIdLoaihang() != null
						&& castOther.getIdLoaihang() != null && this.getIdLoaihang().equals(castOther.getIdLoaihang())))
				&& ((this.getGiamGia() == castOther.getGiamGia()) || (this.getGiamGia() != null
						&& castOther.getGiamGia() != null && this.getGiamGia().equals(castOther.getGiamGia())))
				&& ((this.getImages() == castOther.getImages()) || (this.getImages() != null
						&& castOther.getImages() != null && this.getImages().equals(castOther.getImages())))
				&& ((this.getSoLuong() == castOther.getSoLuong()) || (this.getSoLuong() != null
						&& castOther.getSoLuong() != null && this.getSoLuong().equals(castOther.getSoLuong())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSanpham();
		result = 37 * result + (getTenSanpham() == null ? 0 : this.getTenSanpham().hashCode());
		result = 37 * result + this.getGia();
		result = 37 * result + (getMoTa() == null ? 0 : this.getMoTa().hashCode());
		result = 37 * result + this.getTinhTrang();
		result = 37 * result + (getIdLoaihang() == null ? 0 : this.getIdLoaihang().hashCode());
		result = 37 * result + (getGiamGia() == null ? 0 : this.getGiamGia().hashCode());
		result = 37 * result + (getImages() == null ? 0 : this.getImages().hashCode());
		result = 37 * result + (getSoLuong() == null ? 0 : this.getSoLuong().hashCode());
		return result;
	}

}
