package com.example.demo.entities;
// Generated May 2, 2018 12:42:50 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VLikemost generated by hbm2java
 */
@Entity
@Table(name = "v_likemost", catalog = "shophandmade")
public class VLikemost implements java.io.Serializable {

	private VLikemostId id;

	public VLikemost() {
	}

	public VLikemost(VLikemostId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSanpham", column = @Column(name = "ID_SANPHAM", nullable = false)),
			@AttributeOverride(name = "tenSanpham", column = @Column(name = "TEN_SANPHAM", nullable = false, length = 200)),
			@AttributeOverride(name = "gia", column = @Column(name = "GIA", nullable = false)),
			@AttributeOverride(name = "moTa", column = @Column(name = "MO_TA", length = 500)),
			@AttributeOverride(name = "tinhTrang", column = @Column(name = "TINH_TRANG", nullable = false)),
			@AttributeOverride(name = "idLoaihang", column = @Column(name = "ID_LOAIHANG")),
			@AttributeOverride(name = "giamGia", column = @Column(name = "GIAM_GIA")),
			@AttributeOverride(name = "images", column = @Column(name = "IMAGES", length = 500)),
			@AttributeOverride(name = "soLuong", column = @Column(name = "SO_LUONG")) })
	public VLikemostId getId() {
		return this.id;
	}

	public void setId(VLikemostId id) {
		this.id = id;
	}

}
